version: '3.8'
services:
  app:
    build: .
    depends_on:
      - db
    command: start-local
    env_file: .env
    restart: unless-stopped
    environment:
      DB_HOST: db
    ports:
      - 3000:${EXPOSED_PORT}
    networks:
      standardnotes_proxy:
        aliases:
          - syncing_server
      syncing_server: {}
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    expose:
      - '3306'
    restart: unless-stopped
    volumes:
      - std_notes_db:/var/lib/mysql
    networks:
      - syncing_server

volumes:
  std_notes_db:

networks:
  syncing_server:
    name: syncing_server
  standardnotes_proxy:
    name: standardnotes
