default: &default
  access_token_expiration_time: <%= 60.days %>
  refresh_token_expiration_time: <%= 1.years %>

development:
  <<: *default

test:
  <<: *default
  access_token_expiration_time: <%= 2.seconds %>
  refresh_token_expiration_time: <%= 6.seconds %>

staging:
  <<: *default

production:
  <<: *default
