name: Dev

on:
  push:
    branches: [ develop ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: "changeme123"
          MYSQL_DATABASE: "standard_notes_db"
          MYSQL_USER: "std_notes_user"
          MYSQL_PASSWORD: "changeme123"
        ports:
        - 3306:3306

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Copy default configuration
      run: cp env.sample .env
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rspec

  deploy-web:
    needs: test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: standardnotes/syncing-server
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ github.sha }}"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition syncing-server-dev --query taskDefinition > task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: syncing-server-dev
        image: "standardnotes/syncing-server:${{ github.sha }}"

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: syncing-server-dev
        cluster: dev
        wait-for-service-stability: false

  deploy-worker:
    needs: deploy-web

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish Worker to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        QUEUE: ${{ secrets.SQS_DEV_QUEUE }}
      with:
        name: standardnotes/syncing-server
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "worker-latest,worker-${{ github.sha }}"
        dockerfile: Dockerfile.worker
        buildargs: QUEUE
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition syncing-server-worker-dev --query taskDefinition > worker-task-definition.json
    - name: Fill in the new image worker ID in the Amazon ECS task definition
      id: worker-task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: worker-task-definition.json
        container-name: syncing-server-worker-dev
        image: "standardnotes/syncing-server:worker-${{ github.sha }}"
    - name: Deploy Amazon ECS worker task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.worker-task-def.outputs.task-definition }}
        service: syncing-server-worker-dev
        cluster: dev
        wait-for-service-stability: false
